colorspaces_list = [
    "default",
    "color_picking\tcolor_picking (Output - sRGB)",
    "color_timing\tcolor_timing (ACES - ACEScc)",
    "compositing_linear\tcompositing_linear (ACES - ACEScg)",
    "compositing_log\tcompositing_log (Input - ADX - ADX10)",
    "data\tdata (Utility - Raw)",
    "default\tdefault (ACES - ACES2065-1)",
    "matte_paint\tmatte_paint (Utility - sRGB - Texture)",
    "reference\treference (Utility - Raw)",
    "rendering\trendering (ACES - ACEScg)",
    "scene_linear\tscene_linear (ACES - ACEScg)",
    "texture_paint\ttexture_paint (ACES - ACEScc)",
    "ACES - ACES2065-1\tColorspaces/ACES/ACES - ACES2065-1",
    "ACES - ACEScc\tColorspaces/ACES/ACES - ACEScc",
    "ACES - ACEScct\tColorspaces/ACES/ACES - ACEScct",
    "ACES - ACESproxy\tColorspaces/ACES/ACES - ACESproxy",
    "ACES - ACEScg\tColorspaces/ACES/ACES - ACEScg",
    "Input - ADX - ADX10\tColorspaces/Input/ADX/Input - ADX - ADX10",
    "Input - ADX - ADX16\tColorspaces/Input/ADX/Input - ADX - ADX16",
    "Input - ARRI - V3 LogC (EI160) - Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - V3 LogC (EI160) - Wide Gamut",
    "Input - ARRI - V3 LogC (EI200) - Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - V3 LogC (EI200) - Wide Gamut",
    "Input - ARRI - V3 LogC (EI250) - Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - V3 LogC (EI250) - Wide Gamut",
    "Input - ARRI - V3 LogC (EI320) - Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - V3 LogC (EI320) - Wide Gamut",
    "Input - ARRI - V3 LogC (EI400) - Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - V3 LogC (EI400) - Wide Gamut",
    "Input - ARRI - V3 LogC (EI500) - Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - V3 LogC (EI500) - Wide Gamut",
    "Input - ARRI - V3 LogC (EI640) - Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - V3 LogC (EI640) - Wide Gamut",
    "Input - ARRI - V3 LogC (EI800) - Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - V3 LogC (EI800) - Wide Gamut",
    "Input - ARRI - V3 LogC (EI1000) - Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - V3 LogC (EI1000) - Wide Gamut",
    "Input - ARRI - V3 LogC (EI1280) - Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - V3 LogC (EI1280) - Wide Gamut",
    "Input - ARRI - V3 LogC (EI1600) - Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - V3 LogC (EI1600) - Wide Gamut",
    "Input - ARRI - V3 LogC (EI2000) - Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - V3 LogC (EI2000) - Wide Gamut",
    "Input - ARRI - V3 LogC (EI2560) - Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - V3 LogC (EI2560) - Wide Gamut",
    "Input - ARRI - V3 LogC (EI3200) - Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - V3 LogC (EI3200) - Wide Gamut",
    "Input - ARRI - Curve - V3 LogC (EI800)\tColorspaces/Input/ARRI/Input - ARRI - Curve - V3 LogC (EI800)",
    "Input - ARRI - Linear - ALEXA Wide Gamut\tColorspaces/Input/ARRI/Input - ARRI - Linear - ALEXA Wide Gamut",
    "Input - Canon - Canon-Log - Rec. 709 Daylight\tColorspaces/Input/Canon/Input - Canon - Canon-Log - Rec. 709 Daylight",
    "Input - Canon - Canon-Log - Rec. 709 Tungsten\tColorspaces/Input/Canon/Input - Canon - Canon-Log - Rec. 709 Tungsten",
    "Input - Canon - Canon-Log - DCI-P3 Daylight\tColorspaces/Input/Canon/Input - Canon - Canon-Log - DCI-P3 Daylight",
    "Input - Canon - Canon-Log - DCI-P3 Tungsten\tColorspaces/Input/Canon/Input - Canon - Canon-Log - DCI-P3 Tungsten",
    "Input - Canon - Canon-Log - Cinema Gamut Daylight\tColorspaces/Input/Canon/Input - Canon - Canon-Log - Cinema Gamut Daylight",
    "Input - Canon - Canon-Log - Cinema Gamut Tungsten\tColorspaces/Input/Canon/Input - Canon - Canon-Log - Cinema Gamut Tungsten",
    "Input - Canon - Canon-Log - Rec. 2020 Daylight\tColorspaces/Input/Canon/Input - Canon - Canon-Log - Rec. 2020 Daylight",
    "Input - Canon - Canon-Log - Rec. 2020 Tungsten\tColorspaces/Input/Canon/Input - Canon - Canon-Log - Rec. 2020 Tungsten",
    "Input - Canon - Canon-Log2 - Rec. 2020 Daylight\tColorspaces/Input/Canon/Input - Canon - Canon-Log2 - Rec. 2020 Daylight",
    "Input - Canon - Canon-Log2 - Rec. 2020 Tungsten\tColorspaces/Input/Canon/Input - Canon - Canon-Log2 - Rec. 2020 Tungsten",
    "Input - Canon - Canon-Log2 - Cinema Gamut Daylight\tColorspaces/Input/Canon/Input - Canon - Canon-Log2 - Cinema Gamut Daylight",
    "Input - Canon - Canon-Log2 - Cinema Gamut Tungsten\tColorspaces/Input/Canon/Input - Canon - Canon-Log2 - Cinema Gamut Tungsten",
    "Input - Canon - Canon-Log3 - Rec. 2020 Daylight\tColorspaces/Input/Canon/Input - Canon - Canon-Log3 - Rec. 2020 Daylight",
    "Input - Canon - Canon-Log3 - Rec. 2020 Tungsten\tColorspaces/Input/Canon/Input - Canon - Canon-Log3 - Rec. 2020 Tungsten",
    "Input - Canon - Canon-Log3 - Cinema Gamut Daylight\tColorspaces/Input/Canon/Input - Canon - Canon-Log3 - Cinema Gamut Daylight",
    "Input - Canon - Canon-Log3 - Cinema Gamut Tungsten\tColorspaces/Input/Canon/Input - Canon - Canon-Log3 - Cinema Gamut Tungsten",
    "Input - Canon - Curve - Canon-Log\tColorspaces/Input/Canon/Input - Canon - Curve - Canon-Log",
    "Input - Canon - Curve - Canon-Log2\tColorspaces/Input/Canon/Input - Canon - Curve - Canon-Log2",
    "Input - Canon - Curve - Canon-Log3\tColorspaces/Input/Canon/Input - Canon - Curve - Canon-Log3",
    "Input - Canon - Linear - Canon Rec. 709 Daylight\tColorspaces/Input/Canon/Input - Canon - Linear - Canon Rec. 709 Daylight",
    "Input - Canon - Linear - Canon Rec. 709 Tungsten\tColorspaces/Input/Canon/Input - Canon - Linear - Canon Rec. 709 Tungsten",
    "Input - Canon - Linear - Canon DCI-P3 Daylight\tColorspaces/Input/Canon/Input - Canon - Linear - Canon DCI-P3 Daylight",
    "Input - Canon - Linear - Canon DCI-P3 Tungsten\tColorspaces/Input/Canon/Input - Canon - Linear - Canon DCI-P3 Tungsten",
    "Input - Canon - Linear - Canon Cinema Gamut Daylight\tColorspaces/Input/Canon/Input - Canon - Linear - Canon Cinema Gamut Daylight",
    "Input - Canon - Linear - Canon Cinema Gamut Tungsten\tColorspaces/Input/Canon/Input - Canon - Linear - Canon Cinema Gamut Tungsten",
    "Input - Canon - Linear - Canon Rec. 2020 Daylight\tColorspaces/Input/Canon/Input - Canon - Linear - Canon Rec. 2020 Daylight",
    "Input - Canon - Linear - Canon Rec. 2020 Tungsten\tColorspaces/Input/Canon/Input - Canon - Linear - Canon Rec. 2020 Tungsten",
    "Input - Generic - sRGB - Texture\tColorspaces/Input/Generic/Input - Generic - sRGB - Texture",
    "Input - GoPro - Protune Flat - Protune Native - Experimental\tColorspaces/Input/GoPro/Input - GoPro - Protune Flat - Protune Native - Experimental",
    "Input - GoPro - Curve - Protune Flat\tColorspaces/Input/GoPro/Input - GoPro - Curve - Protune Flat",
    "Input - GoPro - Linear - Protune Native - Experimental\tColorspaces/Input/GoPro/Input - GoPro - Linear - Protune Native - Experimental",
    "Input - Panasonic - V-Log - V-Gamut\tColorspaces/Input/Panasonic/Input - Panasonic - V-Log - V-Gamut",
    "Input - Panasonic - Curve - V-Log\tColorspaces/Input/Panasonic/Input - Panasonic - Curve - V-Log",
    "Input - Panasonic - Linear - V-Gamut\tColorspaces/Input/Panasonic/Input - Panasonic - Linear - V-Gamut",
    "Input - RED - REDlogFilm - DRAGONcolor\tColorspaces/Input/RED/Input - RED - REDlogFilm - DRAGONcolor",
    "Input - RED - REDlogFilm - DRAGONcolor2\tColorspaces/Input/RED/Input - RED - REDlogFilm - DRAGONcolor2",
    "Input - RED - REDlogFilm - REDcolor\tColorspaces/Input/RED/Input - RED - REDlogFilm - REDcolor",
    "Input - RED - REDlogFilm - REDcolor2\tColorspaces/Input/RED/Input - RED - REDlogFilm - REDcolor2",
    "Input - RED - REDlogFilm - REDcolor3\tColorspaces/Input/RED/Input - RED - REDlogFilm - REDcolor3",
    "Input - RED - REDlogFilm - REDcolor4\tColorspaces/Input/RED/Input - RED - REDlogFilm - REDcolor4",
    "Input - RED - REDLog3G10 - REDWideGamutRGB\tColorspaces/Input/RED/Input - RED - REDLog3G10 - REDWideGamutRGB",
    "Input - RED - Curve - REDlogFilm\tColorspaces/Input/RED/Input - RED - Curve - REDlogFilm",
    "Input - RED - Curve - REDLog3G10\tColorspaces/Input/RED/Input - RED - Curve - REDLog3G10",
    "Input - RED - Linear - DRAGONcolor\tColorspaces/Input/RED/Input - RED - Linear - DRAGONcolor",
    "Input - RED - Linear - DRAGONcolor2\tColorspaces/Input/RED/Input - RED - Linear - DRAGONcolor2",
    "Input - RED - Linear - REDcolor\tColorspaces/Input/RED/Input - RED - Linear - REDcolor",
    "Input - RED - Linear - REDcolor2\tColorspaces/Input/RED/Input - RED - Linear - REDcolor2",
    "Input - RED - Linear - REDcolor3\tColorspaces/Input/RED/Input - RED - Linear - REDcolor3",
    "Input - RED - Linear - REDcolor4\tColorspaces/Input/RED/Input - RED - Linear - REDcolor4",
    "Input - RED - Linear - REDWideGamutRGB\tColorspaces/Input/RED/Input - RED - Linear - REDWideGamutRGB",
    "Input - Sony - S-Log1 - S-Gamut\tColorspaces/Input/Sony/Input - Sony - S-Log1 - S-Gamut",
    "Input - Sony - S-Log2 - S-Gamut\tColorspaces/Input/Sony/Input - Sony - S-Log2 - S-Gamut",
    "Input - Sony - S-Log2 - S-Gamut Daylight\tColorspaces/Input/Sony/Input - Sony - S-Log2 - S-Gamut Daylight",
    "Input - Sony - S-Log2 - S-Gamut Tungsten\tColorspaces/Input/Sony/Input - Sony - S-Log2 - S-Gamut Tungsten",
    "Input - Sony - S-Log3 - S-Gamut3\tColorspaces/Input/Sony/Input - Sony - S-Log3 - S-Gamut3",
    "Input - Sony - S-Log3 - S-Gamut3.Cine\tColorspaces/Input/Sony/Input - Sony - S-Log3 - S-Gamut3.Cine",
    "Input - Sony - S-Log3 - Venice S-Gamut3\tColorspaces/Input/Sony/Input - Sony - S-Log3 - Venice S-Gamut3",
    "Input - Sony - S-Log3 - Venice S-Gamut3.Cine\tColorspaces/Input/Sony/Input - Sony - S-Log3 - Venice S-Gamut3.Cine",
    "Input - Sony - Curve - S-Log1\tColorspaces/Input/Sony/Input - Sony - Curve - S-Log1",
    "Input - Sony - Curve - S-Log2\tColorspaces/Input/Sony/Input - Sony - Curve - S-Log2",
    "Input - Sony - Curve - S-Log3\tColorspaces/Input/Sony/Input - Sony - Curve - S-Log3",
    "Input - Sony - Linear - S-Gamut\tColorspaces/Input/Sony/Input - Sony - Linear - S-Gamut",
    "Input - Sony - Linear - S-Gamut Daylight\tColorspaces/Input/Sony/Input - Sony - Linear - S-Gamut Daylight",
    "Input - Sony - Linear - S-Gamut Tungsten\tColorspaces/Input/Sony/Input - Sony - Linear - S-Gamut Tungsten",
    "Input - Sony - Linear - S-Gamut3.Cine\tColorspaces/Input/Sony/Input - Sony - Linear - S-Gamut3.Cine",
    "Input - Sony - Linear - S-Gamut3\tColorspaces/Input/Sony/Input - Sony - Linear - S-Gamut3",
    "Input - Sony - Linear - Venice S-Gamut3\tColorspaces/Input/Sony/Input - Sony - Linear - Venice S-Gamut3",
    "Input - Sony - Linear - Venice S-Gamut3.Cine\tColorspaces/Input/Sony/Input - Sony - Linear - Venice S-Gamut3.Cine",
    "Output - DCDM\tColorspaces/Output/Output - DCDM",
    "Output - DCDM (P3D60 Limited)\tColorspaces/Output/Output - DCDM (P3D60 Limited)",
    "Output - DCDM (P3D65 Limited)\tColorspaces/Output/Output - DCDM (P3D65 Limited)",
    "Output - P3-D60\tColorspaces/Output/Output - P3-D60",
    "Output - P3D65\tColorspaces/Output/Output - P3D65",
    "Output - P3D65 (D60 simulation)\tColorspaces/Output/Output - P3D65 (D60 simulation)",
    "Output - P3D65 (Rec.709 Limited)\tColorspaces/Output/Output - P3D65 (Rec.709 Limited)",
    "Output - P3-DCI (D60 simulation)\tColorspaces/Output/Output - P3-DCI (D60 simulation)",
    "Output - P3-DCI (D65 simulation)\tColorspaces/Output/Output - P3-DCI (D65 simulation)",
    "Output - Rec.2020\tColorspaces/Output/Output - Rec.2020",
    "Output - Rec.2020 (P3D65 Limited)\tColorspaces/Output/Output - Rec.2020 (P3D65 Limited)",
    "Output - Rec.2020 (Rec.709 Limited)\tColorspaces/Output/Output - Rec.2020 (Rec.709 Limited)",
    "Output - Rec.709\tColorspaces/Output/Output - Rec.709",
    "Output - Rec.709 (D60 sim.)\tColorspaces/Output/Output - Rec.709 (D60 sim.)",
    "Output - sRGB\tColorspaces/Output/Output - sRGB",
    "Output - sRGB (D60 sim.)\tColorspaces/Output/Output - sRGB (D60 sim.)",
    "Output - P3-D65 ST2084 (1000 nits)\tColorspaces/Output/Output - P3-D65 ST2084 (1000 nits)",
    "Output - P3D65 ST2084 (108 nits)\tColorspaces/Output/Output - P3D65 ST2084 (108 nits)",
    "Output - P3-D65 ST2084 (2000 nits)\tColorspaces/Output/Output - P3-D65 ST2084 (2000 nits)",
    "Output - P3-D65 ST2084 (4000 nits)\tColorspaces/Output/Output - P3-D65 ST2084 (4000 nits)",
    "Output - Rec.2020 HLG (1000 nits)\tColorspaces/Output/Output - Rec.2020 HLG (1000 nits)",
    "Output - Rec.2020 ST2084 (1000 nits)\tColorspaces/Output/Output - Rec.2020 ST2084 (1000 nits)",
    "Output - Rec.2020 ST2084 (2000 nits)\tColorspaces/Output/Output - Rec.2020 ST2084 (2000 nits)",
    "Output - Rec.2020 ST2084 (4000 nits)\tColorspaces/Output/Output - Rec.2020 ST2084 (4000 nits)",
    "Utility - LMT Shaper\tColorspaces/Utility/Utility - LMT Shaper",
    "Utility - Log2 48 nits Shaper\tColorspaces/Utility/Utility - Log2 48 nits Shaper",
    "Utility - Log2 48 nits Shaper - AP1\tColorspaces/Utility/Utility - Log2 48 nits Shaper - AP1",
    "Utility - Log2 108 nits Shaper\tColorspaces/Utility/Utility - Log2 108 nits Shaper",
    "Utility - Log2 108 nits Shaper - AP1\tColorspaces/Utility/Utility - Log2 108 nits Shaper - AP1",
    "Utility - Log2 1000 nits Shaper\tColorspaces/Utility/Utility - Log2 1000 nits Shaper",
    "Utility - Log2 1000 nits Shaper - AP1\tColorspaces/Utility/Utility - Log2 1000 nits Shaper - AP1",
    "Utility - Log2 2000 nits Shaper\tColorspaces/Utility/Utility - Log2 2000 nits Shaper",
    "Utility - Log2 2000 nits Shaper - AP1\tColorspaces/Utility/Utility - Log2 2000 nits Shaper - AP1",
    "Utility - Log2 4000 nits Shaper\tColorspaces/Utility/Utility - Log2 4000 nits Shaper",
    "Utility - Log2 4000 nits Shaper - AP1\tColorspaces/Utility/Utility - Log2 4000 nits Shaper - AP1",
    "Utility - Dolby PQ 10000\tColorspaces/Utility/Utility - Dolby PQ 10000",
    "Utility - Dolby PQ 48 nits Shaper\tColorspaces/Utility/Utility - Dolby PQ 48 nits Shaper",
    "Utility - Dolby PQ 48 nits Shaper - AP1\tColorspaces/Utility/Utility - Dolby PQ 48 nits Shaper - AP1",
    "Utility - Dolby PQ 108 nits Shaper\tColorspaces/Utility/Utility - Dolby PQ 108 nits Shaper",
    "Utility - Dolby PQ 108 nits Shaper - AP1\tColorspaces/Utility/Utility - Dolby PQ 108 nits Shaper - AP1",
    "Utility - Dolby PQ 1000 nits Shaper\tColorspaces/Utility/Utility - Dolby PQ 1000 nits Shaper",
    "Utility - Dolby PQ 1000 nits Shaper - AP1\tColorspaces/Utility/Utility - Dolby PQ 1000 nits Shaper - AP1",
    "Utility - Dolby PQ 2000 nits Shaper\tColorspaces/Utility/Utility - Dolby PQ 2000 nits Shaper",
    "Utility - Dolby PQ 2000 nits Shaper - AP1\tColorspaces/Utility/Utility - Dolby PQ 2000 nits Shaper - AP1",
    "Utility - Dolby PQ 4000 nits Shaper\tColorspaces/Utility/Utility - Dolby PQ 4000 nits Shaper",
    "Utility - Dolby PQ 4000 nits Shaper - AP1\tColorspaces/Utility/Utility - Dolby PQ 4000 nits Shaper - AP1",
    "Utility - Curve - Rec.1886\tColorspaces/Utility/Utility - Curve - Rec.1886",
    "Utility - Curve - Rec.2020\tColorspaces/Utility/Utility - Curve - Rec.2020",
    "Utility - Curve - Rec.709\tColorspaces/Utility/Utility - Curve - Rec.709",
    "Utility - Curve - sRGB\tColorspaces/Utility/Utility - Curve - sRGB",
    "Utility - Gamma 1.8 - Rec.709 - Texture\tColorspaces/Utility/Utility - Gamma 1.8 - Rec.709 - Texture",
    "Utility - Gamma 2.2 - Rec.709 - Texture\tColorspaces/Utility/Utility - Gamma 2.2 - Rec.709 - Texture",
    "Utility - Linear - Adobe RGB\tColorspaces/Utility/Utility - Linear - Adobe RGB",
    "Utility - Linear - Adobe Wide Gamut RGB\tColorspaces/Utility/Utility - Linear - Adobe Wide Gamut RGB",
    "Utility - Linear - P3-D60\tColorspaces/Utility/Utility - Linear - P3-D60",
    "Utility - Linear - P3-D65\tColorspaces/Utility/Utility - Linear - P3-D65",
    "Utility - Linear - P3-DCI\tColorspaces/Utility/Utility - Linear - P3-DCI",
    "Utility - Linear - RIMM ROMM (ProPhoto)\tColorspaces/Utility/Utility - Linear - RIMM ROMM (ProPhoto)",
    "Utility - Linear - Rec.2020\tColorspaces/Utility/Utility - Linear - Rec.2020",
    "Utility - Linear - Rec.709\tColorspaces/Utility/Utility - Linear - Rec.709",
    "Utility - Linear - sRGB\tColorspaces/Utility/Utility - Linear - sRGB",
    "Utility - Rec.2020 - Camera\tColorspaces/Utility/Utility - Rec.2020 - Camera",
    "Utility - Rec.2020 - Display\tColorspaces/Utility/Utility - Rec.2020 - Display",
    "Utility - Rec.709 - Camera\tColorspaces/Utility/Utility - Rec.709 - Camera",
    "Utility - Rec.709 - Display\tColorspaces/Utility/Utility - Rec.709 - Display",
    "Utility - XYZ - D60\tColorspaces/Utility/Utility - XYZ - D60",
    "Utility - sRGB - Texture\tColorspaces/Utility/Utility - sRGB - Texture",
    "Utility - Raw\tColorspaces/Utility/Utility - Raw",
    "Utility - Look - ACES 1.0 to 0.1 emulation\tColorspaces/Utility/Look/Utility - Look - ACES 1.0 to 0.1 emulation",
    "Utility - Look - ACES 1.0 to 0.2 emulation\tColorspaces/Utility/Look/Utility - Look - ACES 1.0 to 0.2 emulation",
    "Utility - Look - ACES 1.0 to 0.7 emulation\tColorspaces/Utility/Look/Utility - Look - ACES 1.0 to 0.7 emulation",
    "Utility - Look - Blue Light Artifact Fix\tColorspaces/Utility/Look/Utility - Look - Blue Light Artifact Fix",
    "Role - color_picking\tColorspaces/Utility/Roles/Role - color_picking",
    "Role - color_timing\tColorspaces/Utility/Roles/Role - color_timing",
    "Role - compositing_log\tColorspaces/Utility/Roles/Role - compositing_log",
    "Role - data\tColorspaces/Utility/Roles/Role - data",
    "Role - default\tColorspaces/Utility/Roles/Role - default",
    "Role - matte_paint\tColorspaces/Utility/Roles/Role - matte_paint",
    "Role - reference\tColorspaces/Utility/Roles/Role - reference",
    "Role - scene_linear\tColorspaces/Utility/Roles/Role - scene_linear",
    "Role - texture_paint\tColorspaces/Utility/Roles/Role - texture_paint",
    "Role - compositing_linear\tColorspaces/Utility/Roles/Role - compositing_linear",
    "Role - rendering\tColorspaces/Utility/Roles/Role - rendering",
    "lin_ap0\tColorspaces/Utility/Aliases/lin_ap0",
    "aces\tColorspaces/Utility/Aliases/aces",
    "acescc\tColorspaces/Utility/Aliases/acescc",
    "acescc_ap1\tColorspaces/Utility/Aliases/acescc_ap1",
    "acescct\tColorspaces/Utility/Aliases/acescct",
    "acescct_ap1\tColorspaces/Utility/Aliases/acescct_ap1",
    "acesproxy\tColorspaces/Utility/Aliases/acesproxy",
    "acesproxy_ap1\tColorspaces/Utility/Aliases/acesproxy_ap1",
    "acescg\tColorspaces/Utility/Aliases/acescg",
    "lin_ap1\tColorspaces/Utility/Aliases/lin_ap1",
    "adx10\tColorspaces/Utility/Aliases/adx10",
    "adx16\tColorspaces/Utility/Aliases/adx16",
    "logc3ei160_alexawide\tColorspaces/Utility/Aliases/logc3ei160_alexawide",
    "logc3ei200_alexawide\tColorspaces/Utility/Aliases/logc3ei200_alexawide",
    "logc3ei250_alexawide\tColorspaces/Utility/Aliases/logc3ei250_alexawide",
    "logc3ei320_alexawide\tColorspaces/Utility/Aliases/logc3ei320_alexawide",
    "logc3ei400_alexawide\tColorspaces/Utility/Aliases/logc3ei400_alexawide",
    "logc3ei500_alexawide\tColorspaces/Utility/Aliases/logc3ei500_alexawide",
    "logc3ei640_alexawide\tColorspaces/Utility/Aliases/logc3ei640_alexawide",
    "logc3ei800_alexawide\tColorspaces/Utility/Aliases/logc3ei800_alexawide",
    "logc3ei1000_alexawide\tColorspaces/Utility/Aliases/logc3ei1000_alexawide",
    "logc3ei1280_alexawide\tColorspaces/Utility/Aliases/logc3ei1280_alexawide",
    "logc3ei1600_alexawide\tColorspaces/Utility/Aliases/logc3ei1600_alexawide",
    "logc3ei2000_alexawide\tColorspaces/Utility/Aliases/logc3ei2000_alexawide",
    "logc3ei2560_alexawide\tColorspaces/Utility/Aliases/logc3ei2560_alexawide",
    "logc3ei3200_alexawide\tColorspaces/Utility/Aliases/logc3ei3200_alexawide",
    "crv_logc3ei800\tColorspaces/Utility/Aliases/crv_logc3ei800",
    "lin_alexawide\tColorspaces/Utility/Aliases/lin_alexawide",
    "canonlog_rec709day\tColorspaces/Utility/Aliases/canonlog_rec709day",
    "canonlog_rec709tung\tColorspaces/Utility/Aliases/canonlog_rec709tung",
    "canonlog_dcip3day\tColorspaces/Utility/Aliases/canonlog_dcip3day",
    "canonlog_dcip3tung\tColorspaces/Utility/Aliases/canonlog_dcip3tung",
    "canonlog_cgamutday\tColorspaces/Utility/Aliases/canonlog_cgamutday",
    "canonlog_cgamuttung\tColorspaces/Utility/Aliases/canonlog_cgamuttung",
    "canonlog_rec2020day\tColorspaces/Utility/Aliases/canonlog_rec2020day",
    "canonlog_rec2020tung\tColorspaces/Utility/Aliases/canonlog_rec2020tung",
    "canonlog2_rec2020day\tColorspaces/Utility/Aliases/canonlog2_rec2020day",
    "canonlog2_rec2020tung\tColorspaces/Utility/Aliases/canonlog2_rec2020tung",
    "canonlog2_cgamutday\tColorspaces/Utility/Aliases/canonlog2_cgamutday",
    "canonlog2_cgamuttung\tColorspaces/Utility/Aliases/canonlog2_cgamuttung",
    "canonlog3_rec2020day\tColorspaces/Utility/Aliases/canonlog3_rec2020day",
    "canonlog3_rec2020tung\tColorspaces/Utility/Aliases/canonlog3_rec2020tung",
    "canonlog3_cgamutday\tColorspaces/Utility/Aliases/canonlog3_cgamutday",
    "canonlog3_cgamuttung\tColorspaces/Utility/Aliases/canonlog3_cgamuttung",
    "crv_canonlog\tColorspaces/Utility/Aliases/crv_canonlog",
    "crv_canonlog2\tColorspaces/Utility/Aliases/crv_canonlog2",
    "crv_canonlog3\tColorspaces/Utility/Aliases/crv_canonlog3",
    "lin_canonrec709day\tColorspaces/Utility/Aliases/lin_canonrec709day",
    "lin_canonrec709tung\tColorspaces/Utility/Aliases/lin_canonrec709tung",
    "lin_canondcip3day\tColorspaces/Utility/Aliases/lin_canondcip3day",
    "lin_canondcip3tung\tColorspaces/Utility/Aliases/lin_canondcip3tung",
    "lin_canoncgamutday\tColorspaces/Utility/Aliases/lin_canoncgamutday",
    "lin_canoncgamuttung\tColorspaces/Utility/Aliases/lin_canoncgamuttung",
    "lin_canonrec2020day\tColorspaces/Utility/Aliases/lin_canonrec2020day",
    "lin_canonrec2020tung\tColorspaces/Utility/Aliases/lin_canonrec2020tung",
    "protuneflat_protunegamutexp\tColorspaces/Utility/Aliases/protuneflat_protunegamutexp",
    "crv_protuneflat\tColorspaces/Utility/Aliases/crv_protuneflat",
    "lin_protunegamutexp\tColorspaces/Utility/Aliases/lin_protunegamutexp",
    "vlog_vgamut\tColorspaces/Utility/Aliases/vlog_vgamut",
    "crv_vlog\tColorspaces/Utility/Aliases/crv_vlog",
    "lin_vgamut\tColorspaces/Utility/Aliases/lin_vgamut",
    "rlf_dgn\tColorspaces/Utility/Aliases/rlf_dgn",
    "rlf_dgn2\tColorspaces/Utility/Aliases/rlf_dgn2",
    "rlf_rc\tColorspaces/Utility/Aliases/rlf_rc",
    "rlf_rc2\tColorspaces/Utility/Aliases/rlf_rc2",
    "rlf_rc3\tColorspaces/Utility/Aliases/rlf_rc3",
    "rlf_rc4\tColorspaces/Utility/Aliases/rlf_rc4",
    "rl3g10_rwg\tColorspaces/Utility/Aliases/rl3g10_rwg",
    "crv_rlf\tColorspaces/Utility/Aliases/crv_rlf",
    "crv_rl3g10\tColorspaces/Utility/Aliases/crv_rl3g10",
    "lin_dgn\tColorspaces/Utility/Aliases/lin_dgn",
    "lin_dgn2\tColorspaces/Utility/Aliases/lin_dgn2",
    "lin_rc\tColorspaces/Utility/Aliases/lin_rc",
    "lin_rc2\tColorspaces/Utility/Aliases/lin_rc2",
    "lin_rc3\tColorspaces/Utility/Aliases/lin_rc3",
    "lin_rc4\tColorspaces/Utility/Aliases/lin_rc4",
    "lin_rwg\tColorspaces/Utility/Aliases/lin_rwg",
    "slog1_sgamut\tColorspaces/Utility/Aliases/slog1_sgamut",
    "slog2_sgamut\tColorspaces/Utility/Aliases/slog2_sgamut",
    "slog2_sgamutday\tColorspaces/Utility/Aliases/slog2_sgamutday",
    "slog2_sgamuttung\tColorspaces/Utility/Aliases/slog2_sgamuttung",
    "slog3_sgamut3\tColorspaces/Utility/Aliases/slog3_sgamut3",
    "slog3_sgamutcine\tColorspaces/Utility/Aliases/slog3_sgamutcine",
    "slog3_venice_sgamut3\tColorspaces/Utility/Aliases/slog3_venice_sgamut3",
    "slog3_venice_sgamutcine\tColorspaces/Utility/Aliases/slog3_venice_sgamutcine",
    "crv_slog1\tColorspaces/Utility/Aliases/crv_slog1",
    "crv_slog2\tColorspaces/Utility/Aliases/crv_slog2",
    "crv_slog3\tColorspaces/Utility/Aliases/crv_slog3",
    "lin_sgamut\tColorspaces/Utility/Aliases/lin_sgamut",
    "lin_sgamutday\tColorspaces/Utility/Aliases/lin_sgamutday",
    "lin_sgamuttung\tColorspaces/Utility/Aliases/lin_sgamuttung",
    "lin_sgamut3cine\tColorspaces/Utility/Aliases/lin_sgamut3cine",
    "lin_sgamut3\tColorspaces/Utility/Aliases/lin_sgamut3",
    "lin_venice_sgamut3\tColorspaces/Utility/Aliases/lin_venice_sgamut3",
    "lin_venice_sgamut3cine\tColorspaces/Utility/Aliases/lin_venice_sgamut3cine",
    "out_dcdm\tColorspaces/Utility/Aliases/out_dcdm",
    "out_dcdmp3d60limited\tColorspaces/Utility/Aliases/out_dcdmp3d60limited",
    "out_dcdmp3d65limited\tColorspaces/Utility/Aliases/out_dcdmp3d65limited",
    "out_p3d60\tColorspaces/Utility/Aliases/out_p3d60",
    "out_p3d65\tColorspaces/Utility/Aliases/out_p3d65",
    "out_p3d65d60simulation\tColorspaces/Utility/Aliases/out_p3d65d60simulation",
    "out_p3d65rec709limited\tColorspaces/Utility/Aliases/out_p3d65rec709limited",
    "out_p3dcid60simulation\tColorspaces/Utility/Aliases/out_p3dcid60simulation",
    "out_p3dcid65simulation\tColorspaces/Utility/Aliases/out_p3dcid65simulation",
    "out_rec2020\tColorspaces/Utility/Aliases/out_rec2020",
    "out_rec2020p3d65limited\tColorspaces/Utility/Aliases/out_rec2020p3d65limited",
    "out_rec2020rec709limited\tColorspaces/Utility/Aliases/out_rec2020rec709limited",
    "out_rec709\tColorspaces/Utility/Aliases/out_rec709",
    "out_rec709d60sim\tColorspaces/Utility/Aliases/out_rec709d60sim",
    "out_srgb\tColorspaces/Utility/Aliases/out_srgb",
    "out_srgbd60sim\tColorspaces/Utility/Aliases/out_srgbd60sim",
    "out_p3d65st20841000nits\tColorspaces/Utility/Aliases/out_p3d65st20841000nits",
    "out_p3d65st2084108nits\tColorspaces/Utility/Aliases/out_p3d65st2084108nits",
    "out_p3d65st20842000nits\tColorspaces/Utility/Aliases/out_p3d65st20842000nits",
    "out_p3d65st20844000nits\tColorspaces/Utility/Aliases/out_p3d65st20844000nits",
    "out_rec2020hlg1000nits\tColorspaces/Utility/Aliases/out_rec2020hlg1000nits",
    "out_rec2020st20841000nits\tColorspaces/Utility/Aliases/out_rec2020st20841000nits",
    "out_rec2020st20842000nits\tColorspaces/Utility/Aliases/out_rec2020st20842000nits",
    "out_rec2020st20844000nits\tColorspaces/Utility/Aliases/out_rec2020st20844000nits",
    "crv_lmtshaper\tColorspaces/Utility/Aliases/crv_lmtshaper",
    "crv_log248nitsshaper\tColorspaces/Utility/Aliases/crv_log248nitsshaper",
    "log248nitsshaper_ap1\tColorspaces/Utility/Aliases/log248nitsshaper_ap1",
    "crv_log2108nitsshaper\tColorspaces/Utility/Aliases/crv_log2108nitsshaper",
    "log2108nitsshaper_ap1\tColorspaces/Utility/Aliases/log2108nitsshaper_ap1",
    "crv_log21000nitsshaper\tColorspaces/Utility/Aliases/crv_log21000nitsshaper",
    "log21000nitsshaper_ap1\tColorspaces/Utility/Aliases/log21000nitsshaper_ap1",
    "crv_log22000nitsshaper\tColorspaces/Utility/Aliases/crv_log22000nitsshaper",
    "log22000nitsshaper_ap1\tColorspaces/Utility/Aliases/log22000nitsshaper_ap1",
    "crv_log24000nitsshaper\tColorspaces/Utility/Aliases/crv_log24000nitsshaper",
    "log24000nitsshaper_ap1\tColorspaces/Utility/Aliases/log24000nitsshaper_ap1",
    "crv_dolbypq_10000\tColorspaces/Utility/Aliases/crv_dolbypq_10000",
    "crv_dolbypq48nitsshaper\tColorspaces/Utility/Aliases/crv_dolbypq48nitsshaper",
    "dolbypq48nitsshaper_ap1\tColorspaces/Utility/Aliases/dolbypq48nitsshaper_ap1",
    "crv_dolbypq108nitsshaper\tColorspaces/Utility/Aliases/crv_dolbypq108nitsshaper",
    "dolbypq108nitsshaper_ap1\tColorspaces/Utility/Aliases/dolbypq108nitsshaper_ap1",
    "crv_dolbypq1000nitsshaper\tColorspaces/Utility/Aliases/crv_dolbypq1000nitsshaper",
    "dolbypq1000nitsshaper_ap1\tColorspaces/Utility/Aliases/dolbypq1000nitsshaper_ap1",
    "crv_dolbypq2000nitsshaper\tColorspaces/Utility/Aliases/crv_dolbypq2000nitsshaper",
    "dolbypq2000nitsshaper_ap1\tColorspaces/Utility/Aliases/dolbypq2000nitsshaper_ap1",
    "crv_dolbypq4000nitsshaper\tColorspaces/Utility/Aliases/crv_dolbypq4000nitsshaper",
    "dolbypq4000nitsshaper_ap1\tColorspaces/Utility/Aliases/dolbypq4000nitsshaper_ap1",
    "crv_rec1886\tColorspaces/Utility/Aliases/crv_rec1886",
    "crv_rec2020\tColorspaces/Utility/Aliases/crv_rec2020",
    "crv_rec709\tColorspaces/Utility/Aliases/crv_rec709",
    "crv_srgb\tColorspaces/Utility/Aliases/crv_srgb",
    "g18_rec709\tColorspaces/Utility/Aliases/g18_rec709",
    "g22_rec709\tColorspaces/Utility/Aliases/g22_rec709",
    "lin_adobergb\tColorspaces/Utility/Aliases/lin_adobergb",
    "lin_adobewidegamutrgb\tColorspaces/Utility/Aliases/lin_adobewidegamutrgb",
    "lin_p3d60\tColorspaces/Utility/Aliases/lin_p3d60",
    "lin_p3d65\tColorspaces/Utility/Aliases/lin_p3d65",
    "lin_p3dci\tColorspaces/Utility/Aliases/lin_p3dci",
    "lin_prophoto\tColorspaces/Utility/Aliases/lin_prophoto",
    "lin_rimm\tColorspaces/Utility/Aliases/lin_rimm",
    "lin_rec2020\tColorspaces/Utility/Aliases/lin_rec2020",
    "lin_rec709\tColorspaces/Utility/Aliases/lin_rec709",
    "lin_srgb\tColorspaces/Utility/Aliases/lin_srgb",
    "rec2020_camera\tColorspaces/Utility/Aliases/rec2020_camera",
    "rec2020_display\tColorspaces/Utility/Aliases/rec2020_display",
    "rec709_camera\tColorspaces/Utility/Aliases/rec709_camera",
    "rec709_display\tColorspaces/Utility/Aliases/rec709_display",
    "lin_xyz_d60\tColorspaces/Utility/Aliases/lin_xyz_d60",
    "srgb_texture\tColorspaces/Utility/Aliases/srgb_texture",
    "raw\tColorspaces/Utility/Aliases/raw",
    "look_aces10to01emulation\tColorspaces/Utility/Aliases/look_aces10to01emulation",
    "look_aces10to02emulation\tColorspaces/Utility/Aliases/look_aces10to02emulation",
    "look_aces10to07emulation\tColorspaces/Utility/Aliases/look_aces10to07emulation",
    "look_bluelightartifactfix\tColorspaces/Utility/Aliases/look_bluelightartifactfix",
    "role_color_picking\tColorspaces/Utility/Aliases/role_color_picking",
    "role_color_timing\tColorspaces/Utility/Aliases/role_color_timing",
    "role_compositing_log\tColorspaces/Utility/Aliases/role_compositing_log",
    "role_data\tColorspaces/Utility/Aliases/role_data",
    "role_default\tColorspaces/Utility/Aliases/role_default",
    "role_matte_paint\tColorspaces/Utility/Aliases/role_matte_paint",
    "role_reference\tColorspaces/Utility/Aliases/role_reference",
    "role_scene_linear\tColorspaces/Utility/Aliases/role_scene_linear",
    "role_texture_paint\tColorspaces/Utility/Aliases/role_texture_paint",
    "role_compositing_linear\tColorspaces/Utility/Aliases/role_compositing_linear",
    "role_rendering\tColorspaces/Utility/Aliases/role_rendering"
]